### ISSUE TITLE
gulp-concat seems to have been broken with the latest update of your package for Visual Studio users

### ISSUE THREAD

**Issue by koakesdigitalfleet** [floridoo/concat-with-sourcemaps#19]
I don't think this is in any way your responsibility, but I figured I would let you know in case you wanted to do anything about it.

I'm not sure how widespread this is, but as of this morning my gulp-concat tasks in visual studio stopped working. I have already reported an issue to the gulp-concat repo, so you can find the details here
https://github.com/gulp-community/gulp-concat/issues/142

I don't know much about this stuff, but it looks to me like your package may now have a higher node dependency than what visual studio installs by default. I'm sure the workaround is to have visual studio users use a more up to date version of node, but most users don't have that. I'm going to also work on figuring out how to address this, but I just wanted to let you know about the issue

**Comment by robinfhu** [comment]
I suspect it has to do with the latest change in v1.0.6. 

https://github.com/floridoo/concat-with-sourcemaps/issues/20

**Comment by koakesdigitalfleet** [comment]
workaround posted in #20

**Comment by floridoo** [comment]
Should be fixed in v1.0.7.
