### ISSUE TITLE
Version 1.0.6 Breaks with older version of node.js

### ISSUE THREAD

**Issue by robinfhu** [floridoo/concat-with-sourcemaps#20]
Currently on an application with node.js version 0.10.38, and after the latest NPM install, got an error saying
`Buffer has no method 'from'`. 

It appears this is because the `Buffer.from` method was added in a later version of node.js.

I am using `gulp-concat`.

**Comment by jtolla** [comment]
Seeing this as well.

**Comment by robinfhu** [comment]
My solution right now is to add this to my `devDependencies` in package.json:
`"concat-with-sourcemaps": "1.0.5"`

**Comment by syeatts** [comment]
Same. App using gulp-concat where this is listed as version ^1.0.0 broken in node <6 environment. Need backwards compatibility with older node environments.

**Comment by pjklein** [comment]
Florian, d'sollst der Dependenz gegen aeltere node-Versionem einbauen. Koi node-Version-Dependenz heisst "Ich habe mit alle node-Versionen getestet"!

**Comment by pjklein** [comment]
@floridoo, your package.json here on github has "engines" : { "node" : ">= 8.0.0" }, but the package.json in https://registry.npmjs.org/concat-with-sourcemaps/-/concat-with-sourcemaps-1.0.6.tgz is missing the engines property.

**Comment by floridoo** [comment]
Fix for ancient node versions in v1.0.7.

@samizdam, @pjklein: What you describe is the work in progress for v2 (master branch)

**Comment by suketu-rel** [comment]
@floridoo , don't see any v1.0.7 release in github yet, any timeline when this would be available ?
https://github.com/floridoo/concat-with-sourcemaps/releases/tag/v1.0.7

**Comment by pjklein** [comment]
@suketu-rel, it is there now. @floridoo, vielen Dank!
