### ISSUE TITLE
Arbitrarily arrange files position, not just append

### ISSUE THREAD

**Issue by Fiery** [floridoo/concat-with-sourcemaps#9]
Having a use case which requires to concat file based on created dates or names, currently Concat only has a 'push' which appends file.contents to the list. I did a quick fix by adding another function which takes an additional 'fileIndex' argument indicating which position should the file contents go. Not sure if this is on the roadmap and just wondered if this fix can be merged.

**Comment by floridoo** [comment]
Hi @Fiery, you can achieve this by ordering the parts in your own array and then pushing them in the right order.

**Comment by Fiery** [comment]
Well.... anyway I have my own fork worked as expected without creating additional array just to handle this issue, it makes my code clean.
